language: C

compiler:
  - gcc
  - clang

os:
  - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libx11-dev libgtk2.0-dev libxss-dev libcunit1-dev xdotool xvfb

before_script:
  - sudo /sbin/start-stop-daemon --start --quiet --background --exec /usr/bin/Xvfb :99 # start xvfb for idle_timer_test
  - sleep 3 # give xvfb some time to start
  - autoreconf -i

script:
  - export DISPLAY=:99.0
  - ./configure && make && make check && make distcheck

addons:
  artifacts: true
